api/urls.py
from django.conf.urls import url
from api.views import ListCreatePosts, DetailUpdatePost

urlpatterns = [
    url(r'posts/(?P<pk>\d+)', DetailUpdatePost.as_view(),
        name='api_post_detail_update'),
    url(r'posts/top/(?P<top50>\w+)/', ListCreatePosts.as_view(),
        name='api_top_50'),
    url(r'posts/$', ListCreatePosts.as_view(), name='api_post_list_create'),

]

freds_list_evolved/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.decorators.cache import cache_page
from freds_list_evolved import settings
from peteslist.views import LocationList, LocationListHome, UserAccount
from users.views import Register


urlpatterns = [
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^locations/$', LocationList.as_view(), name='list_locations'),
    url(r'^loc/$', LocationListHome.as_view(), name='locs_list'),
    url(r'^locations/(?P<city>.+)/$', 'peteslist.views.loc', name='temp_only'),
    url(r'^register/', Register.as_view(), name='register'),
    url(r'^logout/', 'django.contrib.auth.views.logout',
        {'next_page': '/locations/'}, name='logout'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^posts/', include('peteslist.urls')),
    url(r'^image/', 'peteslist.views.add_image', name='add_image'),
    url(r'^api/', include('api.urls')),
    url(r'^account/$', UserAccount.as_view(), name='account'),
    url(r'^account/delete/(?P<keyword_id>\d+)/$',
        'peteslist.views.delete_keyword', name='delete_keyword'),
    url(r'^regenerate/', 'peteslist.views.regenerate_token',
        name='regenerate'),
    url(r'^google03c5b3464a1f9e6d.html/', 'peteslist.views.wtf')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    # url(r'^loc/$', cache_page(60 * 60)(LocationListHome.as_view()), name='locs_list'),

fredslist/fredslist/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from posting.views import ListCity, CreatePost

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('^', include('django.contrib.auth.urls')),
    url(r'$^', ListCity.as_view(), name='list_city'),
    url(r'^create/$', CreatePost.as_view(), name='create_post'),
    url(r'^api/', include('api.urls')),
]

peteslist/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from peteslist.views import LocationList, LocationListHome, ForSalePost, \
    PostDetail, ListPosts

urlpatterns = [
    url(r'^create/$', login_required(ForSalePost.as_view()), name='post'),
    url(r'^(?P<pk>\d+)/$', PostDetail.as_view(), name='post_detail'),
    url(r'^$', ListPosts.as_view(), name="list_posts"),
    url(r'^cat/(?P<category>.+)/$', ListPosts.as_view(),
        name='category_posts'),
    url(r'^favorite/(?P<post_id>\d+)/', 'peteslist.views.add_favorite',
        name="add_favorite"),
    url(r'^deletefav/(?P<post_id>\d+)/', 'peteslist.views.delete_favorite',
        name="delete_favorite"),
]

peteslist/models.py
from django.contrib.auth.models import User
from django.db import models


class Location(models.Model):
    state = models.CharField(max_length=25)
    city = models.CharField(max_length=40)

    def __str__(self):
        return "{}, {}".format(self.city, self.state)


class Type(models.Model):
    title = models.CharField(max_length=25)

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=35)
    type = models.ForeignKey(Type)

    def __str__(self):
        return self.title


class Post(models.Model):

    CONDITION_CHOICES = (
        ('new', 'New'),
        ('like new', 'Like New'),
        ('excellent', 'Excellent'),
        ('good', 'Good'),
        ('fair', 'Fair'),
        ('salvage', 'Salvage'),
        ('other', 'Other')
        )

    user = models.ForeignKey(User)
    type = models.ForeignKey(Type, null=True)
    category = models.ForeignKey(Category, null=True)
    title = models.CharField(max_length=150)
    description = models.TextField(max_length=5000)
    location = models.ForeignKey(Location, null=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    contact_name = models.CharField(max_length=35, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                null=True, blank=True)
    specific_location = models.CharField(max_length=75, null=True, blank=True)
    condition = models.CharField(choices=CONDITION_CHOICES, null=True,
                                 blank=True, max_length=20)
    by_phone = models.BooleanField(default=False)
    by_text = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    @property
    def favorite_count(self):
        return self.favorite_set.all().count()

    def __str__(self):
        return self.title


class Image(models.Model):
    image = models.ImageField(upload_to='peteslist_images')
    post = models.ForeignKey(Post, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)


class Favorite(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return "Favorite: {}".format(self.post.title)


class Keyword(models.Model):
    keyword = models.CharField(max_length=50)
    user = models.ForeignKey(User, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.keyword

peteslist/forms.py
from django import forms
from django.forms import MultipleChoiceField, ChoiceField
from peteslist.models import Post, Category, Image, Type

CONTACT_CHOICES = (
    ('by_phone', 'By Phone'),
    ('by_text', 'By Text')
    )


class ForSaleForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('type', 'category', 'by_phone', 'by_text', 'phone_number',
                  'contact_name', 'title', 'price', 'specific_location',
                  'description', 'condition')

        widgets = {
            # 'type': forms.TextInput(attrs={'class': 'required'}),
            # 'category': forms.ModelChoiceField(Category.objects.filter(type=type))
            # 'title': forms.TextInput(attrs={'class': 'required'}),
            # 'description': forms.TextInput(attrs={'class': 'required'}),
            # 'by_phone': forms.CheckboxInput(attrs={'class': 'optional'}),
            # 'by_text': forms.CheckboxInput(attrs={'class': 'optional'}),
            # 'phone_number': forms.CheckboxInput(attrs={'class': 'optional'}),
            # 'contact_name': forms.CheckboxInput(attrs={'class': 'optional'}),
            # 'price': forms.CheckboxInput(attrs={'class': 'optional'}),
            # 'specific_location': forms.CheckboxInput(attrs={'class': 'optional'}),
            # 'manufacturer': forms.CheckboxInput(attrs={'class': 'optional'}),
            # 'model_name': forms.CheckboxInput(attrs={'class': 'optional'}),
            # 'serial_num': forms.CheckboxInput(attrs={'class': 'optional'}),
            # 'dimensions': forms.CheckboxInput(attrs={'class': 'optional'}),
            # 'condition': forms.CheckboxInput(attrs={'class': 'optional'})
            # # 'by_phone': forms.BooleanField(attrs={'class': 'form_control'})
        }


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image',)


class SearchForm(forms.Form):
    search = forms.CharField(label='Search', max_length=120)


class KeywordForm(forms.Form):
    keywords = forms.CharField(label='Add Keyword(s)', max_length=50)

peteslist/views.py
import logging
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.forms import formset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView, View, DetailView
from rest_framework.authtoken.models import Token
from peteslist.forms import ForSaleForm, ImageForm, SearchForm, KeywordForm
from peteslist.models import Location, Category, Post, Favorite, Keyword
from django.utils import timezone
from django.db.models import Q, Count

logger = logging.getLogger(__name__)


class LocationList(ListView):
    model = Location

    def dispatch(self, request, *args, **kwargs):
        """
        Check session for location. If there, redirect to city. If not,
          go to home directory.
        :param request: session.location
        :param args:
        :param kwargs:
        :return:
        """
        city = self.request.session.get('location')
        return HttpResponseRedirect(reverse('temp_only',
                                            kwargs={'city': city}))

    def get_context_data(self, **kwargs):
        """
        Separate states into 4 lists.
        :param kwargs:
        :return:
        """
        state_list = []
        context = super().get_context_data(**kwargs)
        for location in Location.objects.all():
            if location.state not in state_list:
                state_list.append(location.state)
        context['page_load'] = timezone.now()
        context['states1'] = state_list[0:13]
        context['states2'] = state_list[13:26]
        context['states3'] = state_list[26:39]
        context['states4'] = state_list[39:]
        return context


class LocationListHome(ListView):
    """ This is a repeat model for a home link with no session check"""
    model = Location
    template_name = 'peteslist/location_home.html'

    def get_context_data(self, **kwargs):
        """
        Separate states into 4 lists.
        :param kwargs:
        :return:
        """
        state_list = []
        context = super().get_context_data(**kwargs)
        for location in Location.objects.all():
            if location.state not in state_list:
                state_list.append(location.state)
        context['page_load'] = timezone.now()
        context['states1'] = state_list[:13]
        context['states2'] = state_list[13:26]
        context['states3'] = state_list[26:39]
        context['states4'] = state_list[39:]
        return context


def loc(request, city):
    """
    Render to city requested. Separate categories into 10 lists.
    Add city to session.
    :param request:
    :param city:
    :return:
    """
    city_list = []
    for location in Location.objects.all():
        city_list.append(location.city)

    if city not in city_list:
        return HttpResponseRedirect(reverse('locs_list'))

    community1 = Category.objects.filter(type__title='community')[:7]
    community2 = Category.objects.filter(type__title='community')[7:]
    housing = Category.objects.filter(type__title='housing')
    for_sale1 = Category.objects.filter(type__title='for sale')[:19]
    for_sale2 = Category.objects.filter(type__title='for sale')[19:]
    services1 = Category.objects.filter(type__title='services')[:10]
    services2 = Category.objects.filter(type__title='services')[10:]
    jobs = Category.objects.filter(type__title='jobs')
    gigs1 = Category.objects.filter(type__title='gigs')[:4]
    gigs2 = Category.objects.filter(type__title='gigs')[4:]
    context_dict = {'community1': community1, 'community2': community2,
                    'housing': housing, 'for_sale1': for_sale1,
                    'for_sale2': for_sale2, 'services1': services1,
                    'services2': services2, 'jobs': jobs,
                    'gigs1': gigs1, 'gigs2': gigs2, 'city': city}
    request.session['location'] = city

    return render(request, 'peteslist/category_list.html', context_dict)


class ForSalePost(View):
    """ Renders home page to Create Post """
    def get(self, request):
        form = ForSaleForm()
        return render(request, 'peteslist/post.html', {'form': form})

    def post(self, *args, **kwargs):
        form = ForSaleForm(self.request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.user = self.request.user
            locate = self.request.session['location']
            post.location = Location.objects.get(city=locate)
            post.save()
            self.request.session['post_id'] = post.id

            return HttpResponseRedirect(reverse('add_image'))

        return render(self.request, 'peteslist/post.html', {'form': form})


def add_image(request):
    """
    Add image to Post
    :param request:
    :return:
    """
    ImageFormSet = formset_factory(ImageForm, extra=5)
    if request.method == 'POST':
        formset = ImageFormSet(request.POST, request.FILES)
        post_id = request.session.get('post_id')
        if formset.is_valid():
            for form in formset:
                if form.is_valid():
                    image = form.save(commit=False)
                    if image.image:
                        image.post = \
                            Post.objects.get(id=post_id)
                        image.save()
        return HttpResponseRedirect(reverse('post_detail',
                                            args=(str(post_id),)))
    else:
        formset = ImageFormSet()
    return render(request, 'peteslist/add_image.html', {'formset': formset})


class ListPosts(ListView):
    model = Post
    paginate_by = 10

    def post(self, catch):
        """
        Add search words to a get url
        :param catch: unused parameter
        :return: HttpResponse with search querystring
        """
        if self.request.method == 'POST':
            form = SearchForm(self.request.POST)
            if form.is_valid():
                search = form.cleaned_data['search']
                return HttpResponseRedirect(reverse('list_posts') +
                                            '?search=' + search)
            else:
                return HttpResponseRedirect(reverse('list_posts'))

    def get_queryset(self):
        """
        Query for post list to return. Location is required. Check for other
        filters including order by top50 most favorited, sort by price, and
        Search words.
        :return: filtered post list
        """
        location = self.request.session.get('location')
        posts = Post.objects.filter(location__city=location)\
            .order_by('-created_at')
        category = self.kwargs.get('category', None)
        if category:
            posts = posts.filter(category__title=category)
        top50 = self.request.GET.get('top50')
        if top50:
            posts = posts.annotate(fav_count=Count('favorite')).\
                order_by('-fav_count')
        sort = self.request.GET.get('sort')
        if sort == 'priceasc':
            posts = posts.order_by('price')
        if sort == 'pricedesc':
            posts = posts.exclude(price=None)
            posts = posts.order_by('-price')
        search = self.request.GET.get('search')
        if search:
            search = search.split()
            q_list = [Q(title__icontains=word) for word in search]
            q_list2 = [Q(description__icontains=word) for word in search]
            q_list = q_list + q_list2
            query = q_list.pop()
            for item in q_list:
                query |= item
            posts = posts.filter(query)
        return posts

    def get_context_data(self, **kwargs):
        """
        Appends one image per post if available.
        Adds Search form to be rendered
        :param kwargs:
        :return:
        """
        context = super().get_context_data(**kwargs)
        context['page_load'] = timezone.now()
        posts = Post.objects.filter(location__city=self.
                                    request.session.get('location'))
        category = self.kwargs.get('category', None)
        if category:
            posts = posts.filter(category__title=category)
        images = []
        for post in posts:
            if post.image_set.all():
                images.append(post.image_set.all()[0])
        context['images'] = images
        form = SearchForm()
        context['form'] = form
        logger.debug("*********ERROR************")
        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        """ Adds image_set """
        context = super().get_context_data(**kwargs)
        b = self.object.image_set.all()
        context['images'] = b
        return context


def add_favorite(request, post_id):
    """
    Create favorite object linked to User and Post.
    Only add if not favorited yet.
    :param request:
    :param post_id:
    :return:
    """
    user = request.user
    post = Post.objects.get(id=post_id)
    for favorite in user.favorite_set.all():
        if favorite.post.id == int(post_id):
            return HttpResponseRedirect(reverse('list_posts'))

    Favorite.objects.create(user=user, post=post)
    return HttpResponseRedirect(reverse('list_posts'))


def delete_favorite(request, post_id):
    """
    Delete favorited post
    :param request:
    :param post_id:
    :return:
    """
    user = request.user
    post = Post.objects.get(id=post_id)
    fav = Favorite.objects.get(post=post, user=user)
    if fav:
        fav.delete()
    return HttpResponseRedirect(reverse('list_posts'))


class UserAccount(ListView):
    model = Post
    template_name = 'peteslist/user_account.html'
    paginate_by = 5

    def dispatch(self, request, *args, **kwargs):
        """ Checks if user is logged in. There is a better way to do this
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        if not self.request.user.id:

peteslist/templates/peteslist/add_image.html
{% extends 'peteslist/base.html' %}
{% load staticfiles %}
{% block content %}

<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ formset.management_form }}
    <table>
        {% for form in formset %}
        {{ form }}
        {% endfor %}
    </table>
    <input type="submit">
    <p>Hit sumbit to continue with no images also</p>
</form>

{% endblock %}

peteslist/templates/peteslist/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/main.css" %}" rel="stylesheet">

</head>
<body>
<div class="container">
    <div class="row" id="top_row_home">
        <div class="col-md-1"></div>
        <div class="col-md-2">
            <a id ="home_logo2" href="{% url 'list_locations' %}">craigslist</a>
        </div>
        <div class="col-md-4">
        </div>
        {% if user.is_authenticated %}
        <div class="col-md-3 head3" id="head3">
            <p>Hello, <strong>{{ user.username }}</strong></p>
            <p><a href="{% url 'account' %}">my account</a> <a href="{%  url 'logout' %}">logout</a></p>
        </div>
        <div class="col-md-2"></div>

        {% else %}
        <div class="col-md-4">
            <p>You are logged out. </p>
            <p>Click to <a href="{%  url 'login' %}">Login</a> or <a href="{% url 'register' %}">Register</a></p>
            <p></p>
        </div>
        <div class="col-md-1">
        </div>
        {% endif %}
    </div><!-- end row -->
{% block content %}{% endblock %}
</div>

<script src="{% static "js/jquery-2.1.4.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>
</body>
</html>

peteslist/templates/peteslist/category_list.html
{% extends 'peteslist/base.html' %}
{% load staticfiles %}
{% load cache %}
{% block content %}
    <div class="row" id="format_home">
        <div class="col-md-1"></div>
        <div class="col-md-2" id="sidebar_left">
            <div id="logo">
                <a href="{% url 'locs_list' %}">craigslist</a>
            </div>
            <div class="tab">
                <ul>
                    <li><a id="post" href="{% url 'post' %}">
                        post to classified</a></li>
                    <li><a href="{% url 'account' %}">my account</a></li>
                    <li><a href="{% url 'register' %}">register</a></li>
                    <li><a href="{% url 'login' %}">login</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-8" id="middle">
            <div id="city_header">
                <h2 class="nolink">{{ city }}</h2>
            </div>
            <div class="col-md-4">
                <h4 class="ban">community</h4>
                <div class="col-md-6 unpad">
                    <ul>
                    {% for listing in community1 %}
                        <li><a href="{% url 'category_posts' listing.title %}">{{ listing }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="col-md-6 unpad">
                    <ul>
                    {% for listing in community2 %}
                        <li><a href="{% url 'category_posts' listing.title %}">{{ listing }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md-5">
                <h4 class="ban">housing</h4>
                <ul>
                {% for listing in housing %}
                    <li><a href="{% url 'category_posts' listing.title %}">{{ listing }}</a></li>
                {% endfor %}
                </ul>
                <h4 class="ban"><a href="{% url 'list_posts' %}">for sale</a></h4>
                <div class="col-md-6 unpad">
                    <ul>
                    {% for listing in for_sale1 %}
                    <li><a href="{% url 'category_posts' listing.title %}">{{ listing.title }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="col-md-6 unpad">
                    <ul>
                    {% for listing in for_sale2 %}
                    <li><a href="{% url 'category_posts' listing.title %}">{{ listing.title }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
                <p></p>
                <h4 class="ban">services</h4>
                <div class="col-md-6 unpad">
                    <ul>
                    {% for listing in services1 %}
                    <li><a href="{% url 'category_posts' listing.title %}">{{ listing }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="col-md-6 unpad">
                    <ul>
                    {% for listing in services2 %}
                    <li><a href="{% url 'category_posts' listing.title %}">{{ listing }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <h4 class="ban">jobs</h4>
                <ul>
                {% for listing in jobs %}
                    <li><a href="{% url 'category_posts' listing.title %}">{{ listing }}</a></li>
                {% endfor %}
                </ul>
            </div>
        </div><!-- end col8 center -->
        <div class="col-md-1"></div>
    </div><!-- End row -->

{% endblock %}

peteslist/templates/peteslist/google03c5b3464a1f9e6d.html
google-site-verification: google03c5b3464a1f9e6d.html

peteslist/templates/peteslist/location_home.html
{% extends 'peteslist/base.html' %}
{% load staticfiles %}
{% load cache %}
{% block content %}
{#    {% cache 3600 slow %}#}
    <h1 id="home_logo">craigslist</h1>
    <div class="tab">
        <ul id="home-nav">
            <li><a href="#">US</a></li>
            <li><a href="#">Canada</a></li>
            <li><a href="#">Europe</a></li>
            <li><a href="#">Asia/Pacific/Middle East</a></li>
            <li><a href="#">Oceania</a></li>
            <li><a href="#">Latin America</a></li>
            <li><a href="#">Africa</a></li>
        </ul>
    </div>

    <div class="row" id="loc-row">
        <div class="col-md-3">
            {% for state in states1 %}
                <h4>{{ state }}</h4>
                <ul>
                {% for location in location_list %}
                    {% if location.state == state %}
                        <li><a href="{% url 'temp_only' location.city %}">{{ location.city }}</a></li>
                    {% endif %}
                {% endfor %}
                </ul>
            {% endfor %}
        </div>
        <div class="col-md-3">
            {% for state in states2 %}
                <h4>{{ state }}</h4>
                <ul>
                {% for location in location_list %}
                    {% if location.state == state %}
                        <li><a href="{% url 'temp_only' location.city %}">{{ location.city }}</a></li>
                    {% endif %}
                {% endfor %}
                </ul>
            {% endfor %}
        </div>
        <div class="col-md-3">
            {% for state in states3 %}
                <h4>{{ state }}</h4>
                <ul>
                {% for location in location_list %}
                    {% if location.state == state %}
                        <li><a href="{% url 'temp_only' location.city %}">{{ location.city }}</a></li>
                    {% endif %}
                {% endfor %}
                </ul>
            {% endfor %}
        </div>
        <div class="col-md-3">
            {% for state in states4 %}
                <h4>{{ state }}</h4>
                <ul>
                {% for location in location_list %}
                    {% if location.state == state %}
                        <li><a href="{% url 'temp_only' location.city %}">{{ location.city }}</a></li>
                    {% endif %}
                {% endfor %}
                </ul>
            {% endfor %}
        </div>
    </div><!-- End row -->
{#    {% endcache %}#}
{% endblock %}

peteslist/templates/peteslist/location_list.html
{% extends 'peteslist/base.html' %}
{% load staticfiles %}
{% load cache %}
{% block content %}
    {% cache 3600 slow %}
    <h1 id="home_logo">craigslist</h1>
    <div class="tab">
        <ul id="home-nav">
            <li><a href="#">US</a></li>
            <li><a href="#">Canada</a></li>
            <li><a href="#">Europe</a></li>
            <li><a href="#">Asia/Pacific/Middle East</a></li>
            <li><a href="#">Oceania</a></li>
            <li><a href="#">Latin America</a></li>
            <li><a href="#">Africa</a></li>
        </ul>
    </div>

    <div class="row">
        <div class="col-md-3">
            {% for state in states1 %}
                <h4>{{ state }}</h4>
                <ul>
                {% for location in location_list %}
                    {% if location.state == state %}
                        <li><a href="{% url 'temp_only' location.city %}">{{ location.city }}</a></li>
                    {% endif %}
                {% endfor %}
                </ul>
            {% endfor %}
        </div>
        <div class="col-md-3">
            {% for state in states2 %}
                <h4>{{ state }}</h4>
                <ul>
                {% for location in location_list %}
                    {% if location.state == state %}
                        <li><a href="{% url 'temp_only' location.city %}">{{ location.city }}</a></li>
                    {% endif %}
                {% endfor %}
                </ul>
            {% endfor %}
        </div>
        <div class="col-md-3">
            {% for state in states3 %}
                <h4>{{ state }}</h4>
                <ul>
                {% for location in location_list %}
                    {% if location.state == state %}
                        <li><a href="{% url 'temp_only' location.city %}">{{ location.city }}</a></li>
                    {% endif %}
                {% endfor %}
                </ul>
            {% endfor %}
        </div>
        <div class="col-md-3">
            {% for state in states4 %}
                <h4>{{ state }}</h4>
                <ul>
                {% for location in location_list %}
                    {% if location.state == state %}
                        <li><a href="{% url 'temp_only' location.city %}">{{ location.city }}</a></li>
                    {% endif %}
                {% endfor %}
                </ul>
            {% endfor %}
        </div>
    </div><!-- End row -->
    {% endcache %}
{% endblock %}

peteslist/templates/peteslist/post_detail.html
{% extends 'peteslist/base.html' %}
{% load staticfiles %}
{% block content %}

    <h2>{{ post.title }}</h2>
    <ul>
        <li>User: {{ post.user }}</li>
        <li>Description: {{ post.description }}</li>
        <li>Location: {{ post.location }}</li>
        <li>Phone: {{ post.phone_number }}</li>
        <li>By phone: {{ post.by_phone }}</li>
        <li>By text: {{ post.by_text }}</li>
        <li>Contact Name: {{ post.contact_name }}</li>
        <li>Price: {{ post.price }}</li>
        <li>Condition: {{ post.condition }}</li>
        <li>Created at: {{ post.created_at }}</li>
    </ul>

    {% for image in images %}
        <p><img src="{{ image.image.url }}"></p>
    {% endfor %}

{% endblock %}

peteslist/templates/peteslist/user_account.html
{% extends 'peteslist/base.html' %}
{% load staticfiles %}
{% block content %}
    <form action="{% url 'account' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add Keyword">
    </form>
    <ul>
        {% for keyword in keywords %}
        <li>
            {{ keyword.keyword }}
            <span><a href="{% url 'delete_keyword' keyword.id %}">delete</a></span>
        </li>
        {% endfor %}
    </ul>
    <h3>{{ user.username }} Token: </h3>
    <p>{{ key }}</p>
    <p><a href="{% url 'regenerate' %}">regenerate</a></p>
    <h3>{{ user.username }} Posts: </h3>
    <ul id="post-list">
    {% for post in post_list %}
        <h4><a href="{% url 'post_detail' post.id %}">{{ post.title }}</a></h4>
        <span><a href="{% url 'add_favorite' post.id %}">Favorite</a></span>
        {% for thing in post.favorite_set.all %}
            {% if thing.user == user %}
                <p>FAVORITED!!!</p>
                <span><a href="{% url 'delete_favorite' post.id %}">DELETE</a></span>
            {% endif %}
        {% endfor %}
        <li>
            <ul>
                {% if not post.image_set.all %}
                    <img src="{% static 'images/craigslist.jpeg'%}">
                {% endif %}
                {% for image in images %}
                    {% if image.post == post %}
                        <li><img src="{{ image.image.url }}"></li>
                    {% endif %}
                {% endfor %}
                {% if post.price %}
                    <li>${{ post.price }}</li>
                {% endif %}
            </ul>
        </li>
    {% endfor %}
    {% if is_paginated %}
    {% if page_obj.has_previous %}
        <a href="{% url 'account' %}?page={{ page_obj.previous_page_number }}"><-Prev</a>
    {% endif %}
    {{ page_obj }}
    {% if page_obj.has_next %}
        <a href="{% url 'account' %}?page={{ page_obj.next_page_number }}">Next -></a>
    {% endif %}
{% endif %}
    </ul>
{% endblock %}